# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master
    - feature/*
  paths:
    include:
    - chainvayler/*
    - bank-sample/*

resources:
- repo: self

variables:
  tag: '0.$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Docker build Chainvayler image
      inputs:
        command: build
        repository: raft/chainvayler
        dockerfile: '$(Build.SourcesDirectory)/chainvayler/Dockerfile'
        tags: |
          $(tag)
          latest
          dev
    - task: Docker@2
      displayName: 'Docker push Chainvayler image: master'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        command: push
        containerRegistry: docker_hub_connection_raft
        repository: raft/chainvayler
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: 'Docker push Chainvayler image: feature/'
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'))
      inputs:
        command: push
        containerRegistry: docker_hub_connection_raft
        repository: raft/chainvayler
        tags: |
          $(tag)
          dev
    - task: Docker@2
      displayName: Docker build Bank sample image
      inputs:
        command: build
        repository: raft/chainvayler-bank-sample
        dockerfile: '$(Build.SourcesDirectory)/bank-sample/Dockerfile'
        arguments: --build-arg chainvayler_tag=$(tag)
        tags: |
          $(tag)
          latest
          dev
    - task: Docker@2
      displayName: 'Docker push Bank sample image: master'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        command: push
        containerRegistry: docker_hub_connection_raft
        repository: raft/chainvayler-bank-sample
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: 'Docker push Bank sample image: feature/'
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'))
      inputs:
        command: push
        containerRegistry: docker_hub_connection_raft
        repository: raft/chainvayler-bank-sample
        tags: |
          $(tag)
          dev
