# sample
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chainvayler-sample-reader-writer
spec:
  replicas: {{ .Values.replication.enabled | ternary .Values.replication.readerWriterCount 0 }}
  podManagementPolicy: Parallel
  serviceName: chainvayler-sample-reader-writer
  selector:
    matchLabels:
      name: chainvayler-sample-reader-writer
  volumeClaimTemplates:
  {{- if and .Values.persistence.enabled .Values.persistence.mountVolumes }}
  - metadata:
      name: peer-disk
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: {{ $.Values.persistence.storageClass }}
      resources:
        requests:
          storage: {{ $.Values.persistence.diskSize }}
  {{- end }}
  template:
    metadata:
      labels:
        name: chainvayler-sample-reader-writer
        hazelcast: chainvayler-sample
    spec:
      volumes:
      {{- if not (and .Values.persistence.enabled .Values.persistence.mountVolumes) }}
      - name: peer-disk
        emptyDir: {}
      {{- end }}
      - name: logging-config
        configMap:
           name: chainvayler-logging-config

      containers:
      - name: chainvayler-sample-reader-writer
        image: raft/chainvayler-bank-sample:{{- .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        
        command: ["sh", "-c", "java -Xmx{{- .Values.java.maxMemory }} \
                    {{- if .Values.java.enableAssertions }}
                    -ea \
                    {{- end }}
                    -Dhazelcast.shutdownhook.policy=GRACEFUL \
                    -Dhazelcast.logging.type={{- .Values.hazelcast.logging.type }} \
                    -Djava.util.logging.config.file=/chainvayler-bank-sample/logging.properties \
                    -cp $(cat /chainvayler-bank-sample/classpath) raft.chainvayler.samples.bank.Main \
                    --readers {{ .Values.load.readers }} \
                    --writers {{ .Values.load.writers }} \
                    --actions {{ .Values.load.actions }} \
                    --replication {{ .Values.replication.enabled }} \
                    --persistence {{ .Values.persistence.enabled }} \
                    --txIdReserveSize 0 \
                    --kubernetes true \
                    --kubernetesServiceName chainvayler-sample-hazelcast.{{- .Release.Namespace }}.svc.cluster.local \
                    --peerStatsRegistry chainvayler-peer-stats \
                    --hazelcastAsyncBackupCount {{ .Values.hazelcast.mapConfig.asyncBackupCount }} \
                    --debug {{ .Values.chainvayler.debug }}" ]

        volumeMounts:
        - name: peer-disk
          mountPath: /chainvayler-bank-sample/persist/
        - name: logging-config
          subPath: logging.properties
          mountPath: /chainvayler-bank-sample/logging.properties
          
